### ISSUE TITLE
0 [main] lftp 922 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)

### ISSUE THREAD

**Issue by TheMafia442** [userdocs/lftp-windows#10]
Hi, I am getting this issue with the latest release. It still works though. Just errors like this then starts downloading.

      0 [main] lftp 911 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      0 [main] lftp 911 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      0 [main] lftp 914 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      0 [main] lftp 914 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      1 [main] lftp 921 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      1 [main] lftp 921 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      0 [main] lftp 922 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      0 [main] lftp 922 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      0 [main] lftp 923 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
      0 [main] lftp 923 child_info_fork::abort: \??\C:\Users\User\Desktop\lftp-test\lftp-windows-master\system\bin\cygz.dll: Loaded to different address: parent(0x170000) != child(0x1B0000)
`...UbuntuLinux.ISO', got 864616448 of 3622323816 (23%) 8.71M/s eta:6m
oo........ooo........ooo........ooo........oo.........oo........ooo........oo.........ooo........oo.........

**Comment by userdocs** [comment]
As in the 1.4.0 release or the master zip file from the main repo?

**Comment by TheMafia442** [comment]
Hi Mate - The master zip in the main Repo

**Comment by TheMafia442** [comment]
I just downloaded the 1.4.0 and it is working fine. My bad.

**Comment by userdocs** [comment]
I am aware of the issue with the main repo. I am just looking at the best way to resolve it. 

There has been no lftp version change since 1.4.0 and current master.

**Comment by userdocs** [comment]
This should be fixed in the main repo. Test and confirm please.
