### ISSUE TITLE
openssh/openssl

### ISSUE THREAD

**Issue by copaceticgeek** [userdocs/lftp-windows#11]
It is no longer possible to install the correct versions of openssh (7.9) and openssl (1.0.2) from cygwin setup. Oldest selectable openssh is 8.0p 1-2 and openssl is 1.1.1b-1.

**Comment by userdocs** [comment]
OK, thanks for bringing this to my attention.

I verified this issue, the problem is how to work around it. This fundamentally breaks lftp in Cygwin so i feel Cygwin need to remedy this issue, i am just not sure how to properly reach out to them for a resolution.

**Comment by userdocs** [comment]
Please see 

https://github.com/lavv17/lftp/issues/547

https://github.com/lavv17/lftp/issues/525

**Comment by userdocs** [comment]
I am working on a method to generate the known hosts file using openssh to totally bypass this issue. I have the basic idea working . It just needs a little work to be ready to push.

**Comment by userdocs** [comment]
Can you test with this commit: https://github.com/userdocs/LFTP4WIN-CORE/commit/4f750db4a0e5895fe1a495afa2aa12d26b44f7af

It should work for all options.

**Comment by copaceticgeek** [comment]
Sorry I haven't had a chance to get back to you. Here's what I get when trying to mirror to local
`touch: cannot touch '/cygdrive/c/Users/XYZ/Downloads/LFTP4WIN/home/.ssh/known_hosts': No such file or directory
do_known_hosts: hostkeys_foreach failed: No such file or directory
C:\Users\XYZ\Downloads\LFTP4WIN\system\applications\conemu\..\..\bin\bash: /cygdrive/c/Users/XYZ/Downloads/LFTP4WIN/home/.ssh/known_hosts: No such file or directory
sort: cannot read: /cygdrive/c/Users/XYZ/Downloads/LFTP4WIN/home/.ssh/known_hosts: No such file or directory
C:\Users\XYZ\Downloads\LFTP4WIN\system\applications\conemu\..\..\bin\bash: /cygdrive/c/Users/XYZ/Downloads/LFTP4WIN/home/.ssh/known_hosts: No such file or directory`

**Comment by userdocs** [comment]
Is this using fresh  download of the repo or an updated but existing installation?

**Comment by copaceticgeek** [comment]
Fresh download to test. When I ran installer the cygwin installer didn't pop up to select packages to install. It just downloaded the necessary files and completed, no errors.

**Comment by userdocs** [comment]
Its hard to say without knowing more. You can use the discord for that.

The main point is that file should be created. I am not sure why it wasn't.

________________________________

**Comment by copaceticgeek** [comment]
FYI, if I copy over the known_hosts file from a previous working build, it works and transfers fine without errors.

**Comment by userdocs** [comment]
So fully fixed with this commit, thanks for the assistance in identifying the issues.

https://github.com/userdocs/LFTP4WIN-CORE/commit/8ec6eda2d0b87c7da12d92a0724092d2f0174205
