### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Beanstown** [userdocs/lftp-windows#12]
did a fresh install of lftp4win and am getting a segmentation fault error whenever i try and download something with pget to local, also happened using built in updater which is why i tried the clean install to rule out it being an updater issue.

**Comment by userdocs** [comment]
That is because of lftp 4.9 you can run the update bat to downgrade it until 4.9.1 (released last night) is added to cygwin

**Comment by Beanstown** [comment]
awesome, that worked. thanks for the tip and also thanks for this project its greatly appreciated :)
