### ISSUE TITLE
Installer Failing

### ISSUE THREAD

**Issue by AndreWattz** [userdocs/lftp-windows#13]
Batch file fails right after "Installing [Cygwin Portable]", and it seems to happen @ line 114 with the bitsadmin download command for Cygwin. I have tried editing the config's customization options, manually starting the BITS service, browsed past issues here for any solutions related to this and I'm at a loss. I had a previous installation setup on the machine , which is running Windows 7 x64, that installed fine but folder was since deleted. Maybe a conflict with the previous install/leftovers? 

Thanks for your time and all your work in bringing this project to life!

**Comment by userdocs** [comment]
Do you have a firewall application or firewall control on this system?

**Comment by AndreWattz** [comment]
Just the built- in standard Windows firewall, which I get exception
notifications for when an application requests approval. Nothing for the
installer came up this time or the previous successful install. However, to
rule this out I did previously disable the firewall completely to no avail.

**Comment by AndreWattz** [comment]
Just the built- in standard Windows firewall, which I get exception notifications for when an application requests approval. Nothing for the installer came up this time or the previous successful install. However, to rule this out I did previously disable the firewall completely to no avail.

**Comment by AndreWattz** [comment]
Just the built- in standard Windows firewall, which I get exception notifications for when an application requests approval. Nothing for the installer came up this time or the previous successful install. However, to rule this out I did previously disable the firewall completely to no avail.

**Comment by AndreWattz** [comment]
Just the built- in standard Windows firewall, which I get exception notifications for when an application requests approval. Nothing for the installer came up this time or the previous successful install. However, to rule this out I did previously disable the firewall completely to no avail.

**Comment by AndreWattz** [comment]
Just the built- in standard Windows firewall, which I get exception notifications for when an application requests approval. Nothing for the installer came up this time or the previous successful install. However, to rule this out I did previously disable the firewall completely to no avail.

**Comment by userdocs** [comment]
You can change this https://github.com/userdocs/LFTP4WIN/blob/447250ae04174ab6bbf2aed0e705b11532aa819a/LFTP4WIN-installer.cmd#L1 to just `@echo on` maybe see some other useful info

**Comment by AndreWattz** [comment]
Not too sure what I'm looking for but the last goto:fail I can see occurs here

[](https://github.com/userdocs/LFTP4WIN/blob/447250ae04174ab6bbf2aed0e705b11532aa819a/LFTP4WIN-installer.cmd#L114)

Seems to be selecting the correct x64 setup file for cygwin.  Shows a 1>NUL goto:fail 
followed by     if exist "" (del "" )       .....Is there supposed to be a "%DOWNLOADER% between those "" ?
Then, comes the error message  "Installing [LFTP4WIN Portable] FAILED!"

Does this indicate that it's not able to download the setup file from the mirror and/or install it once downloaded?

Also, are there any known leftovers from the previous install that could be causing conflicts or any sort? I've since scrubbed through the registry and found some leftover entries remaining pertaining to cygwin, conemu, winscp, etc.

**Comment by AndreWattz** [comment]
Not too sure what I'm looking for but the last goto:fail I can see occurs here

https://github.com/userdocs/LFTP4WIN/blob/447250ae04174ab6bbf2aed0e705b11532aa819a/LFTP4WIN-installer.cmd#L114

Seems to be selecting the correct x64 setup file for cygwin.  Shows a 1>NUL goto:fail 
followed by     if exist "" (del "" )       .....Is there supposed to be a "%DOWNLOADER% between those "" ?
Then, comes the error message  "Installing [LFTP4WIN Portable] FAILED!"

Does this indicate that it's not able to download the setup file from the mirror and/or install it once downloaded?

Also, are there any known leftovers from the previous install that could be causing conflicts or any sort? I've since scrubbed through the registry and found some leftover entries remaining pertaining to cygwin, conemu, winscp, etc.

**Comment by userdocs** [comment]
I am making progress

1: The mian issue seems to be an argument is used that the Windows 7 version does not support. Removing `/DYNAMIC` from both lines fixes this issue.

```
bitsadmin /transfer cygwin /download /priority FOREGROUND "https://cygwin.org/%CYGWIN_SETUP%" "%INSTALL_TEMP%\%CYGWIN_SETUP%" > NUL || goto :fail
```

2: This creates a secondary problem that seems to have been introduced by the Windows updates and/or service packs where it won't download over a https url but only http. this works for the cygwin URL but no the github URL.

```
ERROR CODE:    0x80072f7d - An error occurred in the secure channel support
ERROR CONTEXT: 0x00000005 - The error occurred while the remote file was being processed.
```

Still trying to figure out why this https issues occurs.

**Comment by userdocs** [comment]
Ok, so this is pretty much the problem and there is no obvious fix for Windows 7.

Dynamic is required to get content from Github using bitsadmin tranfers. Windows 7 had an older version of this program (7.5) that does not support the dynamic argument.

So you have a choice to do this manually.

Step 1: apply the easyfix from here. https://support.microsoft.com/en-gb/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi and reboot your system to fix the https issue (scroll down to find the easy fix)

Step 2: Use the modified installer i made for this issue:

Download and use this ` LFTP4WIN-installer.cmd ` instead

https://gist.github.com/userdocs/e58fc388da59aa98429fb4ecad49110b

Step 3: Install the LFTP-CORE manually:

Download the zip https://github.com/userdocs/LFTP4WIN-CORE/archive/master.zip

You need to extract the contents of the folder in the archive to the top level of the installation folder.

So copy this

![1](https://user-images.githubusercontent.com/16525024/90836785-32580080-e348-11ea-8d6e-72a1e9eefb14.jpg)

To this and merge all folder and copy and replace all files

![2](https://user-images.githubusercontent.com/16525024/90836802-41d74980-e348-11ea-8341-024793e58e8a.jpg)

Step 4:  Run the `LFTP4WIN-updater.bat` and select `y` to both prompts.

Once that completes it should be installed and functional. All other downloads are done using curl via cygwin.

**Comment by AndreWattz** [comment]
Removing /DYNAMIC from both lines let it complete the install on my end, but that's strange because unless something in the batch file changed in the last ~5 months or so, the initial install I did on the same Win 7 x64 system worked flawlessly w/o editing anything.

What's also interesting is the secure channel support error there. I just diagnosed some Schannel errors that have been popping up in Event Viewer that I've stopped by following this:

https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi

I thought those could of been attributed to the installer failing, but I had not changed to TLS 1.2 until well after the 2nd install of LFTP4WIN was giving me the failure message. Enabling TLS support for Win 7, which is off by default, should resolve the secure channel errors. Also, iirc Windows 8 & 10 has this enabled by default.

However, now assuming everything has installed correctly, when using pget I'm getting the terminal to pop up instead of ConEmu that fully utilized the .conf settings to max out connection. Will continue troubleshooting this and update...thanks again for your help and time!

**Comment by AndreWattz** [comment]
Ok, so I've done several installs of the initial way and more recently, the modified installer -> manual merge that you suggested. The install and updater both say succeeded. 

I do, however, see this message:  *"Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access."*

Also, upon successful install should the custom command buttons look exactly like this?

![](https://raw.githubusercontent.com/userdocs/LFTP4WIN-CORE/master/help/docs/readme-images/commands.jpg)

Because after starting up WinSCP, the buttons are in a completely different order, have some extra commands like OpenSSH & Terminal, and is missing ConEmu. Not sure if this is due to an update or not.

Furthermore, the lftp.conf file does not seem to be applying changes. I can use the override to force the changes to increase pget/mirror connections, but it states to use edits in the .conf file. When the override does increase connections, I show ssh processes in Task Manager, whereas before iirc lftp processes were being propagated :thinking:

**Comment by userdocs** [comment]
This is nothing to do with LFTP4WIN.

`Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access."`

I need to update the picture. This are the new commands. Terminal replaces Conemu as a command. 

![2020-08-23_20-21-44](https://user-images.githubusercontent.com/16525024/90986910-6ddc1000-e57e-11ea-94b4-1c829cbc128b.jpg)

You can now select your preferred terminal.

![2020-08-23_20-22-13](https://user-images.githubusercontent.com/16525024/90986916-7df3ef80-e57e-11ea-8c83-1ecc40f5c2c7.jpg)

Sorry, I don't understand the last paragraph.

**Comment by AndreWattz** [comment]
>*"Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access."*

This message appears in the command prompt window near the end of the installer/updater batch files and seems to be tied to Cygwin from a quick Google search. Not sure if normal or not just bringing it to your attention as I have nothing McAfee related installed on the system.

I did find those configuration options for the buttons right after the last message and good to know about the new custom command buttons and Terminal replacing ConEmu. Thanks for that info


As for the last paragraph. hopefully some clarification....

When one wants to add more connections/parts when grabbing a file via pget for example, should one edit 
set pget:default-n **x**    where x = desired # of parts in the Lftp.conf or the Lftp-conf-override via the custom buttons? 
The Lftp-conf-override.sh seems to be the only one of the two that applies the changes, so I'm guessing that's the correct way?


Lastly, after increasing the # of connections for pget, I'll go to grab a file via pget. Speeds are great (25MB/s +)....
but when I look in the *Processes tab within Task Manager* .......



![](https://raw.githubusercontent.com/userdocs/LFTP4WIN-CORE/master/help/docs/readme-images/speeds.jpg)



I'll see the correct number of additional "connections" via pget that will show up as their own process under this tab which is normal. So for n=25, I'll see an additional 25 processes listed. However, these processes are listed as ssh.exe when I seem to 
recall, in my initial install of LFTP4WIN, these be lftp.exe processes. Shouldn't LFTP4WIN be using lftp to download or am I missing something?
