### ISSUE TITLE
missing files and menu options not responding

### ISSUE THREAD

**Issue by Dan-Heinz** [userdocs/lftp-windows#18]
I'm getting an error message that i'm missing mintty,exe and also when I click on lftp conf option in the menu bar nothing happens. notepad++ doesn't load as it says it should

**Comment by userdocs** [comment]
It's not really enough info to go on. I have tested the installer and it works.

![image](https://user-images.githubusercontent.com/16525024/116424081-227aaf80-a839-11eb-9f53-7871fc2c92af.png)

You'd need to provider more info into what you are doing and how. screens of the installer completing. Stuff like that.

**Comment by Dan-Heinz** [comment]
I realized what I did. I downloaded the zip file containing everything and not the installer. Thank you for your response

**Comment by userdocs** [comment]
Glad you got it sorted
