### ISSUE TITLE
The sheduled taask wont delete the local files

### ISSUE THREAD

**Issue by VinukaThejana** [userdocs/lftp-windows#19]
If i delete the file in my seedbox, it wont delete the Local file even though the remote file is not there

**Comment by userdocs** [comment]
https://lftp.yar.ru/lftp-man.html

![image](https://user-images.githubusercontent.com/16525024/118650323-35e7bd80-b7dc-11eb-9bd2-6285f3611d74.png)

add it to the sync command option

https://userdocs.github.io/LFTP4WIN-CORE/#/commands?id=lftpsync-setup

**Comment by VinukaThejana** [comment]
Thanks for the quick reply, It worked 👍 :)
