### ISSUE TITLE
When using "Mirror to Dir" or "Mirror"

### ISSUE THREAD

**Issue by fxceptioN** [userdocs/lftp-windows#2]
I get this error and bash just immediately closes. I cannot figure out why.,

Assertion "stack_ptr>0" failed: file "/home/ASchulma/dev/cygwin/lftp/lftp-4.7.8-2.x86_64/src/lftp-4.7.8/src/SMTask.cc", line 161, function: static void SMTask::Leave(SMTask*)

**Comment by userdocs** [comment]
What are your script settings? pget and parallel?

![image](https://user-images.githubusercontent.com/16525024/43989400-35ab1668-9d41-11e8-8bd6-d4cca777bf42.png)

**Comment by userdocs** [comment]
Also,  this path makes no sense as it is not part of the package, but it looks like a local cygwin installation path. 

```
/home/ASchulma/dev/cygwin/lftp/lftp-4.7.8-2.x86_64/src/lftp-4.7.8/src/SMTask.cc"
```

The lftp for windows package has it's own environment that is localized.

So is there a conflict here with another program. I wonder if you have ConEmu installed on your system and that is loading with its own environment settings and loading the wrong lftp.

Do you have ConEmu installed, if so remove it and to test.

**Comment by fxceptioN** [comment]
That's not my local path,  I'm using windows.

![](https://puu.sh/BcnoN/78cac3bec4.png)

**Comment by userdocs** [comment]
Do you have Cygwin installed?

**Comment by fxceptioN** [comment]
I had cygwin installed, I installed it to see if it would get rid of the error, and it still does the same thing.

**Comment by userdocs** [comment]
in the help folder, use the start conemu bat and do this command:

```
echo $PATH
```

What does it say?

**Comment by fxceptioN** [comment]
[ ~/scripts] echo $PATH
/usr/bin
[ ~/scripts]

**Comment by userdocs** [comment]
Are you using the latest release? 1.3.3

Does the issue persist with another server?

**Comment by fxceptioN** [comment]
I used this link to download. https://github.com/userdocs/lftp-windows/releases/latest 

have not tried another server. Don't have one to try it on.

**Comment by userdocs** [comment]
Can you try v1.3.2 and see if the issue is still there with this previous version

**Comment by userdocs** [comment]
Try this?

https://github.com/userdocs/lftp-windows/releases/tag/1.3.4

**Comment by userdocs** [comment]
Is this resolved?

**Comment by fxceptioN** [comment]
I just downloaded the latest release and I will try it out this weekend and let you know. Sorry it took me so long to reply.

**Comment by userdocs** [comment]
1.3.5. released.

Test this.
