### ISSUE TITLE
Mirror to local doesn't always do parallel files

### ISSUE THREAD

**Issue by Dan-Heinz** [userdocs/lftp-windows#20]
When I select multiple files and attempt mirror to local sometimes I get only one file that downloads at a time and other times I will get multiple files. What am I missing? I have it set to download parallel or multiple files simultaneously but It will only pull one at a time. I am not using any of the winscp download buttons. How can I troubleshoot?

**Comment by userdocs** [comment]
Mirror to local is for folders. Pget is for files. That is how the commands work.

**Comment by Dan-Heinz** [comment]
sorry to clarify I'm selecting multiple folders

**Comment by userdocs** [comment]
multi selection is not a supported feature due to how winscp manages this. You downloa a single file or folder and queue the rest by repeating the download command process

**Comment by Dan-Heinz** [comment]
so it will only download parallel files if the folder contains multiple files

**Comment by userdocs** [comment]
Yes. But you can symlink folders into a dir that you mirror to overcome this. The problem here is how winscp handles multi selection. I have not found a way to handle this. So thebsymlinknmethod is the best of you really need to parallel download folders
