### ISSUE TITLE
Mirror Only Downloading One File at a Time

### ISSUE THREAD

**Issue by ElementalCrisis** [userdocs/lftp-windows#22]
Hello,

I seem to be doing something wrong because I can't seem to get pget to work when using the ``mirror-to-local`` command. It opens the terminal and begins the download, but it only seems to be downloading one file with one pget request at a time. I have no issue when running ``pget-to-local`` but I'd like to not have to manually select all the files within a folder, if possible. 

Additionally, I must be blind but what parameter or setting do I add to make it auto-add files to my queue instead of asking me if I want to queue them? 

I've attached the lftp.conf file and the overrides file below in case I set something up wrong.

lftp.conf
```
# debug 10 -o "~/lftp-debug.log"
set bmk:save-passwords true
set cache:enable no
set cmd:default-protocol sftp
set cmd:move-background true
set cmd:move-background-detach true
set cmd:parallel 5
set cmd:prompt "lftp \\[\\e[01;32m\\]\\h\\[\\e[00m\\]:\\[\\e[01;34m\\]\\w\\[\\e[00m\\] % "
set cmd:queue-parallel 5
set color:use-color auto
set dns:cache-enable no
set dns:order "inet inet6"
set ftp:ssl-allow true
set ftp:ssl-auth TLS
set ftp:ssl-force true
set ftp:ssl-protect-data true
set ftp:ssl-protect-list true
set ftps:initial-prot P
set log:enabled no
set log:enabled/xfer no
set log:level/debug 10
set log:max-size 5M
set mirror:parallel-directories yes
set mirror:parallel-transfer-count 5
set mirror:set-permissions off
set mirror:use-pget-n 20
set net:reconnect-interval-base 10
set net:timeout 10
set pget:default-n 20
set pget:min-chunk-size 50M
set sftp:auto-confirm yes
set sftp:connect-program "ssh -a -x"
set ssl:verify-certificate false
set xfer:temp-file-name *.lftp
set xfer:use-temp-file yes
```

lftp-conf-override-sh

```
# Options should be set or modified in the /etc/lftp.conf and applied globally if not editable here.
#
# Here you can customize some settings for the mirror command that will override the lftp.conf defaults.
#
# This is where you can set the command switches for the mirror command.
mirror_args='-c'
# Optional - The number of parallel files to download with the mirror command.
# If this variable is empty or 0 the lftp.conf settings will be used instead.
mirror_parallel_transfer_count='5'
# Optional - Set the number of connections per file lftp can open when using the mirror command.
# If this variable is empty or 0 the lftp.conf settings will be used instead.
mirror_use_pget_n='20'
#
# Here you can customize some settings for the pget command that will override the lftp.conf defaults.
#
# This is where you can set the command switches for the pget command.
pget_args='-c'
# Optional - Set the number of connections per file lftp can open when using the pget command.
# If this variable is empty or 0 the lftp.conf settings will be used instead.
pget_default_n='20'
#
```

Thanks for this program and for taking the time to read this issue. :)

**Comment by userdocs** [comment]
The first query is answered by the docs on the relevant repo.

https://userdocs.github.io/LFTP4WIN-CORE/#/commands?id=custom-command-configuration

https://userdocs.github.io/LFTP4WIN-CORE/#/commands?id=mirror-to-local

The second query is that lftp cycles through parallel downloads int the terminal and does not show them all in one go.

You need to monitor your resource usage/ task manager to see what is or isn't being used.

https://www.ghacks.net/2017/12/28/a-detailed-windows-resource-monitor-guide/

**Comment by ElementalCrisis** [comment]
> The first query is answered by the docs on the relevant repo.
> 
> https://userdocs.github.io/LFTP4WIN-CORE/#/commands?id=custom-command-configuration
> 
> https://userdocs.github.io/LFTP4WIN-CORE/#/commands?id=mirror-to-local

I see there should be a window that opens and the option to select "Skip Queue Confirmation", but that window doesn't show when I click the command. 

> The second query is that lftp cycles through parallel downloads int the terminal and does not show them all in one go.
> 
> You need to monitor your resource usage/ task manager to see what is or isn't being used.

Ah I see, that makes sense and after testing it does seem everything is working as intended.

**Comment by userdocs** [comment]
You need change it via the commands options.

![](https://userdocs.github.io/LFTP4WIN-CORE/assets/img-docs/custom-commands-config.jpg)

**Comment by ElementalCrisis** [comment]
Perfect, thank you very much for the assistance!
