### ISSUE TITLE
cygwin drops x86 support, script changes required 

### ISSUE THREAD

**Issue by glodomorrapl** [userdocs/lftp-windows#23]
**fork of the installer with fixed 32-bit support: https://github.com/glodomorrapl/LFTP4WIN-LEGACY**

--------------

script no longer runs properly on x86 systems due to cygwin starting to drop x86 support: 
- https://cygwin.com/pipermail/cygwin/2022-November/252542.html
- http://www.crouchingtigerhiddenfruitbat.org/Cygwin/timemachine.html

the current version of cygwin errors out on x86 systems by default. to get it going on 32-bit windows 7, cygwin mirror in line 47 needs to be set to `http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/2022/11/23/063457` and the `--allow-unsupported-windows option` parameter needs to be added to line 123.

the script also needs to be altered to fetch cygwin 3.3.6 (setup 2.924) on x86 systems, as that version is the last one that's going to support x86 with those extra parameters.

**Comment by userdocs** [comment]
To be honest I don't think I want to do this in the main script. I have no particular interest in supporting x86 as this project is targeted to x86_64 anyway. The first line of the read is 

> This is a deployment tool that allows you to install a portable and configured Cygwin x64 installation to use with the [LFTP4WIN-CORE](https://github.com/userdocs/LFTP4WIN-CORE) solution.

It would be better if you forked the script it and made the changes and/or i'll just pin the issue so others can made the required modifications themselves.

**Comment by glodomorrapl** [comment]
ok done: https://github.com/glodomorrapl/LFTP4WIN-LEGACY

i am clueless about github or software licensing in general, if there is anything i need to change, please let me know and i'll comply

**Comment by userdocs** [comment]
You just add your credits above mine here to be inline with the Apache license.

https://github.com/glodomorrapl/LFTP4WIN-LEGACY/blob/master/LFTP4WIN-installer.cmd#L8

Like i did above the original script credits.

https://github.com/glodomorrapl/LFTP4WIN-LEGACY/blob/master/LFTP4WIN-installer.cmd#L12

That's it really.
