### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by chloyster** [userdocs/lftp-windows#24]
When I run the `LFTP4WIN-installer.cmd` file, the script stops early after only displaying the following
![image](https://github.com/userdocs/LFTP4WIN/assets/15004447/5998da92-be78-4167-863f-2ff1d2c49be7)

I am on Windows 11 home x64

If any other info is needed I will happily provide

**Comment by userdocs** [comment]
Can you just check nothing is deleting it, like an antivirus app/Windows defender?

**Comment by chloyster** [comment]
Hm. Im looking around but dont see anything. Windows defender is all I have and it hasnt really had any special setup. Is there a certain part of it that would cause this?

Edit: There is also nothing recent on protection history

**Comment by chloyster** [comment]
Oh I think I see the issue. The path is not properly resolving for these downloaded files. Its saving them as a whole filename in the root dir

![image](https://github.com/userdocs/LFTP4WIN/assets/15004447/e5b4840c-af9f-410e-b229-43bc0b34b00d)

**Comment by userdocs** [comment]
I cannot replicate the issue on Windows 11 Pro x64.

Unless the issue is Windows 11 home x64 specific.

**Comment by chloyster** [comment]
The files that are downloaded and missing from system/tmp are those ones with the weird names. I just edited the script to not delete them, and moved them into the folder. The script then ran fine and I was able to use the program.

I have no idea why this would be happening, but this has at least solved my issue for the moment.
