### ISSUE TITLE
Conemu error 

### ISSUE THREAD

**Issue by cloudintrousers** [userdocs/lftp-windows#3]
Latest version of lftp-windows, OS windows 10. I get the following message when clicking pget or lftp options. Everything else works fine. I did have cygwin installed previously but uninstalled it. When I open conemu from the help folder and enter echo $path I get:
 [ ~/scripts] echo $PATH
/usr/bin
[ ~/scripts]
The error message is:

![conemu error](https://user-images.githubusercontent.com/42266145/43998675-344af220-9e4f-11e8-9b70-e3103901ba27.JPG)

**Comment by userdocs** [comment]
How do you start the program? do you use the bat file in the documents/lftp folder or did you create a shortcut on your desktop?

**Comment by userdocs** [comment]
I am going to have to come back to this as i cannot replicate the issue. Can you try 1.3.2 and see if the issue is there with that previous version?

**Comment by cloudintrousers** [comment]
Yes I did create a shortcut on my desktop. Unfortunately my laptop screen isn't working so I cant reinstall an earlier version.

________________________________

**Comment by cloudintrousers** [comment]
reinstalled latest version on new laptop. Im able to connect to server and pget single pdf files but not larger folders.  I get the below on conemu
![image](https://user-images.githubusercontent.com/42266145/44516361-01bd3c00-a719-11e8-8611-0a265095d4b3.png)

**Comment by userdocs** [comment]
Why did you close this?

**Comment by cloudintrousers** [comment]
Sorry, I selected the wrong option.

**Comment by cloudintrousers** [comment]
This is now working perfectly! For multiple files, I use mirror instead of Pget and download to the default download lftp folder. Thank you

**Comment by userdocs** [comment]
can you try this release?

https://github.com/userdocs/lftp-windows/releases/tag/1.3.4

**Comment by cloudintrousers** [comment]
Downloads from remote to local file via Pget and mirror now without above error. Problem solved!
Two other issues:
1) When I select a file to upload from local to remote location, mirror option doesn't.
 work (no error message given)
2) Not a big deal, but how to I change the default download folder to a different destination folder?

**Comment by userdocs** [comment]
1: i have never really considered uploading. i don't think it works at this minute.

2: you can do it in the relevant script. they are located in the `system/scripts` folder. you will need to edit the matching script to the command you wish to use.

It's commented in the scripts:

```
# This local path is relative to the portable directory - Use the cygwin path format to specify full local paths - /cygdrive/c/download = C:\download
local_dir="$HOME/../downloads"
```

**Comment by userdocs** [comment]
#.

Ex x

**Comment by userdocs** [comment]
Is this resolved?

**Comment by cloudintrousers** [comment]
Yes, Thanks.
