### ISSUE TITLE
Winscp crashes during mirror transfer

### ISSUE THREAD

**Issue by musikman9** [userdocs/lftp-windows#4]
Winscp crashes after a while during transfer. This happened twice in the last two hours. The Conemu window disappears, but the Conemu process keeps downloading.

**Comment by userdocs** [comment]
Winscp crashing should have no effect on the conemu process. It spawns and run separately of Winscp. So Winscp crashing is most likely unrelated to this app unless the conditions of the crash are specific to using the custom commands.

**Comment by userdocs** [comment]
Any updates?
