### ISSUE TITLE
can't exclude specific file types by setting filter masks in WinSCP

### ISSUE THREAD

**Issue by kruzchy** [userdocs/lftp-windows#5]
Noob question,  
If I set filter masks in WinSCP>Preferences, it doesn't apply to the synchronization process. Is it because we're overriding the default settings with the settings in the script? How do I add file constraints to the synchronization?   
For example, I want to only sync video files and ignore when a png,jpg or literally any other file is seen.    
Sorry if this wasn't the right place to ask.   
Thanks.

**Comment by userdocs** [comment]
Did you find your solution?

**Comment by kruzchy** [comment]
Not exactly but something similar. I use lftp-windows to sync data from seedbox as instructed by sonarr/radarr. So I noticed "Ignore extra files like nfo,srt etc" option which solved my problem directly but no,I didn't manage to find how to do it using filter masks.   
Thanks for taking the time to respond.

**Comment by userdocs** [comment]
Winscp and the lftp conemu process are separate. Winscp only iniates the process via a custom command. For a task scheduled sync Winscp is not even used.

There is a command switch variable in the relevant script. It will most likely be here with an lftp specific command that you exclude file types. For example

https://unix.stackexchange.com/questions/217711/lftp-exclude-file-extensions
