### ISSUE TITLE
Multiple instances with same lock(only one instance should be able to sync at a point of time)

### ISSUE THREAD

**Issue by kruzchy** [userdocs/lftp-windows#6]
Is it possible to run multiple instances of lftp terminal to sync 2 different directories? If so, how?    
I request you to dumb down the solution for me. I've tried having 2 copies of the lftp-windows project but they both run simultaneously but I want only one of them to initiate the download and other to wait till the first instance completes it's work.    
Sorry if this is too obvious, I'm not really familiar with the terminal or lftp.
Thanks.

**Comment by userdocs** [comment]
This sounds to me like a queuing system. The functionality is not there currently but i think it would be possible to add. I'll have to look into it.

**Comment by userdocs** [comment]
This will be the next feature i work on.  Hopefully for release 1.3.6.

**Comment by userdocs** [comment]
Try this v1.3.6:

It has a queue system built into the Mirror to local or Pget to Local commands.

See here for the updated [readme](https://github.com/userdocs/lftp-windows/blob/master/README.md)

https://github.com/userdocs/lftp-windows/releases/latest

**Comment by userdocs** [comment]
Any update to this issue?

**Comment by userdocs** [comment]
I am closing this because the issue was resolved and there has been no response.
