### ISSUE TITLE
access failed when using pget through gui and console interface

### ISSUE THREAD

**Issue by user-steven** [userdocs/lftp-windows#8]
I'm not sure what I did, but I can't seem to pull any files through lftp anymore. I am able to pull files with WinScp, just not through any of the LFTP commands. The last thing I remember doing was force closing several consoles because I accidentally tried to pull too many files. I'm still learning how to use lftp, so I haven't messed around with any automation. Everything is pretty much untouched except the server being added through the WinScp interface.

I've tried the same setting on my laptop and it works fine. It's just when I do it on my main computer I get the following error and the console closes immediately.
https://i.imgur.com/T8eBpeH.png

I've googled the following error "pget: access failed: failure" and can't seem to find anything on the subject either.

**Comment by userdocs** [comment]
the first thing to do is un-comment `debug 10` in the `lftp.conf` and see if the console tells you what the error is.

You can use the custom command to open it.

**Comment by user-steven** [comment]
https://i.imgur.com/H5IVZiR.png
this is what I seem to get and I found this piece of information, but it's for WinSCP

> 
Code 4 (Failure)
Note that not all servers use all codes. Most SSH/SFTP servers, including the most commonly used OpenSSH, support only SFTP version 3 that defines only codes 0 to 8.

These servers would generally use code 4 (Failure) for many errors for which there is a specific code defined in the later versions of SFTP protocol, such as:

Renaming a file to a name of already existing file.
1) Creating a directory that already exists.
2) Moving a remote file to a different filesystem (HDD).
3) Uploading a file to a full filesystem (HDD).
4) Exceeding a user disk quota.
In this case the server is required to provide meaningful description of the error itself (see above). Unfortunately, OpenSSH SFTP server uses always description “Failure”. Is such case, there is unfortunately no way to tell a reason of the failure.

>

1) I'm not renaming any files and everything is uniquely named
2) Directory does not exist on my file system
3) Just downloading
4) My drive capacity is good

I think my situation might be similar to this person https://github.com/userdocs/lftp-windows/issues/3

I tried mirror and that seems to be okay. It might be because I'm trying to pull a folder with multiple files inside? Can't seem to see why pget local doesn't work for that though.

**Comment by userdocs** [comment]
Are you using pget to download a single file or a directory?

**Comment by user-steven** [comment]
A directory

**Comment by userdocs** [comment]
Pget only works for a single file. Mirror only works for a directory.

**Comment by user-steven** [comment]
Ah thank you. I appreciate the support 👍
