### ISSUE TITLE
Incredibly high disk usage and lftp freeze

### ISSUE THREAD

**Issue by BryceReedman** [userdocs/lftp-windows#9]
Either using mirroring or pget the disk usage is constantly quite high with write speeds of around 70-80  MB/s which disrupts work performed on that particular drive and produces concerns in regards to SSD life. Additionally when i am initially downloading a file lftp seems to freeze but the console appears to respond. when this occurs there is no internet activity but the disk usage is still high likewise when it is downloading. to get it to download for some reason ctl + x at times seems to kick it to download otherwise i restart and hope for the best. I'm happy to provide additional information if it helps diagnosing the problem.

**Comment by userdocs** [comment]
1: Disk usage - please provide further information. I don't really understand your issue.

2: lftp in the console will freeze while allocating space for a large file but continues as normal once this is done. The time taken to do this depends on the size of the file.

**Comment by BryceReedman** [comment]
Ahh i see, all is good. i was confused because i was dling very large files. all as intended.

**Comment by userdocs** [comment]
I have understood what real cause of this was and it has been fixed in the almost ready LFTP4WIN 2.0

There is a special cygwin setting for sparse files which prevents the lockup and large files download normally.

https://github.com/userdocs/LFTP4WIN/blob/master/system/etc/fstab#L11
